project:
  type: website
  output-dir: docs

website:
  title: "Oscar Predictions"
  description: "Our Python package for predicting Oscar winners"
  site-url: https://pmprobst.github.io/OscarPredictions/

  navbar:
    background: primary
    left:
      - text: "Home"
        href: site/index.md
      - text: "Documentation"
        href: site/documentation.md
      - text: "Tutorial"
        href: site/tutorial.qmd
      - text: "Technical Report"
        href: site/report.md
      - text: "Streamlit App"
        href: https://oscarpredictions.streamlit.app/
    right:
      - icon: github
        href: https://github.com/pmprobst/OscarPredictions

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true